//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG3_Mini_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG3_Mini_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CharacterCreationAppearanceVisuals {
            get {
                object obj = ResourceManager.GetObject("CharacterCreationAppearanceVisuals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarves : 11333346-bc64-4020-a6f8-7b9587db6e25
        ///Elves : 2c17490c-7b67-2ca8-ffd7-14e9c50db79b
        ///Githyanki : 16564a73-2c40-82c9-7f72-11f07e78c783
        ///Halfling: 44c3666a-cf33-93d0-bb9e-5879d4bfe0da
        ///Human : eec2c59b-f568-8b75-2ab0-ebd5f84a8285
        ///Tiefling : 05ffe01d-815c-844b-5366-124429552988.
        /// </summary>
        internal static string Eye_Materials {
            get {
                return ResourceManager.GetString("Eye Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drow/Elf;
        ///
        ///ELF_F_NKD_Head_A : 93d670df-8e3d-7c35-01f8-cef6b2b83746
        ///ELF_F_NKD_Head_B : 4d2f62a6-fa3e-34bf-0c30-5f5c5162f2a1
        ///ELF_F_NKD_Head_C : b9fa4715-c747-e99c-173c-9d6d417a992e
        ///ELF_F_NKD_Head_D : 489d7f2c-9839-e1d0-67c5-260294337785
        ///ELF_F_NKD_Head_E : 01942843-9367-5f4a-22f8-27505d90287d
        ///ELF_F_NKD_Head_F : 3ceae978-6218-ba21-4eae-82fa956b842f
        ///ELF_F_NKD_Head_G : 7c32a03d-4873-ee77-e869-72c404b4c2b4
        ///ELF_F_NKD_Head_H : a25cc69e-c487-0199-6465-46ff787f5c0c
        ///ELF_F_NKD_Head_Florrick : bbe4f44b-5b96-2f3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Head_Materials {
            get {
                return ResourceManager.GetString("Head Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Head_Merged {
            get {
                object obj = ResourceManager.GetObject("Head_Merged", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Head_Merged_MaterialTexture {
            get {
                object obj = ResourceManager.GetObject("Head_Merged_MaterialTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Head_Merged_Skeleton {
            get {
                object obj = ResourceManager.GetObject("Head_Merged_Skeleton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] meta {
            get {
                object obj = ResourceManager.GetObject("meta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaceUUID so you can quickly replace the above with your desired race
        ///	Deep Gnome: 3560f4a2-c0b8-4f8b-baf8-6b6eaef0c160
        ///	Drow: 4f5d1434-5175-4fa9-b7dc-ab24fba37929
        ///	Dwarf: 0ab2874d-cfdc-405e-8a97-d37bfbb23c52
        ///	Elf: 6c038dcb-7eb5-431d-84f8-cecfaf1c0c5a
        ///	Githyanki: bdf9b779-002c-4077-b377-8ea7c1faa795
        ///	Gnome: f1b3f884-4029-4f0f-b158-1f9fe0ae5a0d
        ///	HalfElf/Drow: 45f4ac10-3c89-4fb2-b37d-f973bb9110c0
        ///	Halfling: 78cd3bcc-1c43-4a2a-aa80-c34322c16a04
        ///	Human: 0eb594cb-8820-4be6-a58d-8be7a1a98fba
        ///	Tiefling: b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Races {
            get {
                return ResourceManager.GetString("Races", resourceCulture);
            }
        }
    }
}
